spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: "${go.id}"
                        client-secret: "${go.secret}"
