spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: "${google.id}"
                        client-secret: "${google.secret}"
